### ISSUE TITLE
Breaking Changes in 2.1.1

### ISSUE THREAD

**Issue by dworthen** [gov4git/gov4git#172]
@petar, I noticed that the plurality and roadmap community repos have updated to v2.1.1 of the protocol while the desktop app is still on 2.0.3. This update appears to have introduced breaking changes. The app is now experiencing the following error:

![image](https://github.com/gov4git/gov4git/assets/624870/4117ac23-5a0e-4739-9ff5-c9fbccf3a57d)

I believe the same is true between versions 2.0.3 and 2.0.4 since 2.0.4 introduces the new data format for errors. I think it is important that all updates under a single major release are forward and backward compatible. You can imagine even if the hosted app is on the latest version of the protocol that an individual may not have opened the application in a few weeks so upon opening the app it will be on an older version until the auto update mechanism has a chance to upgrade. It is important that the CLI client supports both older and newer versions of the protocol under the same major version that way the app does not crash upon launching and has a chance to upgrade.

**Comment by petar** [comment]
@dworthen This is not an incompatibility bug. This is a plain bug (pertaining to which packages are linked in the binary) which I've removed in v2.1.1. Which cli version is being used by the desktop UI in this error message?

I agree with what you say above, otherwise. Note that the new data format for errors doesn't break compatibility, because this is specific to the interface with the desktop app. The desktop app can never end up with a cli that produces the unexpected error output format, right?

**Comment by petar** [comment]
@dworthen I agree with what you are saying. This is an unintentional compatibility bug.
An old client encounters motions with new policy names and is not handling them gracefully.
